### ISSUE TITLE
compliance operator replica set not being removed

### ISSUE THREAD

**Issue by stujb** [openshift/compliance-operator#802] opened 2022-03-03 14:47 UTC
Having deployed compliance-operator 0.1.48 we are finding that the csv is not going to a completed state due to the following 

```
$ oc get csv
 NAME                          DISPLAY               VERSION   REPLACES              PHASE
compliance-operator.v0.1.48   Compliance Operator   0.1.48                          Installing
```

```
status:
  cleanup: {}
  conditions:
  - lastTransitionTime: "2022-03-03T14:35:32Z"
    lastUpdateTime: "2022-03-03T14:35:32Z"
    message: 'installing: deployment changed old hash=b6b58d4d7, new hash=566c8996cf'
    phase: InstallReady
    reason: InstallWaiting
  - lastTransitionTime: "2022-03-03T14:35:33Z"
    lastUpdateTime: "2022-03-03T14:35:33Z"
    message: waiting for install components to report healthy
    phase: Installing
    reason: InstallSucceeded
  - lastTransitionTime: "2022-03-03T14:35:33Z"
    lastUpdateTime: "2022-03-03T14:35:33Z"
    message: 'installing: deployment changed old hash=b6b58d4d7, new hash=566c8996cf'
    phase: InstallReady
    reason: InstallWaiting
  - lastTransitionTime: "2022-03-03T14:35:33Z"
    lastUpdateTime: "2022-03-03T14:35:33Z"
    message: waiting for install components to report healthy
    phase: Installing
    reason: InstallSucceeded
```

Checking in the openshift-compliance project there are two replicasets for the compliance-operator - one with the old hash that has 0 desired replicas and 1 with the new hash that has 1 desired replica and is running correctly

When I attempt to manually delete the old replicaset object it is immediately recreated with the owner being the compliance-operator deployment resource

```
$ oc get rs
NAME                                          DESIRED   CURRENT   READY   AGE
compliance-operator-54b5897d54                0         0         0       4m48s
compliance-operator-6785964f5d                1         1         1       4h38m
```

```
generation: 1
  labels:
    name: compliance-operator
    pod-template-hash: 6785964f5d
  name: compliance-operator-6785964f5d
  namespace: openshift-compliance
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: compliance-operator
    uid: 16f5d036-b3bd-4675-ab7e-0892d0959978
  resourceVersion: "1046053"
  uid: 34c8b54b-dfef-470d-ab90-58db602b18c4
```

We are running `okd 4.9.0-0.okd-2022-01-29-035536`

**Comment by jhrozek** [comment] 2022-03-07 15:01
(btw all those objects are in the `openshift-compliance` namespace)

**Comment by jhrozek** [comment] 2022-03-09 13:44
Matt suggested on Slack that this issue is probably a bug caused by us adding the EKS manifests, fixed by 473eae5fa3eba3d74f146c55cec53b7ed1136276. The bug will be fixed in the next version, to be released in a couple of week.s

**Comment by stujb** [comment] 2022-03-14 12:48
Thanks for the update @jhrozek 

Will wait for the next release and check once we have it deployed

**Comment by stujb** [comment] 2022-03-29 07:30
Have updated to 0.1.49 and verified that this issue no longer occurs in this release

**Closed** 2022-03-29 08:47 UTC
